version: "3.1"

services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
