openapi: 3.0.3
info:
  description: This is a simple -- even too simple -- API for todo notes.
  version: 1.0.0
  title: Simple Todo API
servers: 
  - url: http://localhost:8080/v1
tags:
  - name: notes
    description: Everything about your notes
paths:
  /notes:
    get:
      tags:
        - notes
      summary: Find all notes
      description: Returns all notes
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      tags:
        - notes
      summary: Add a new note
      description: Tries to craete a new note and returns a message
      requestBody:
        required: true
        description: Note object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '200':
          description: Successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
     
  /notes/{noteId}:
    get:
      tags:
        - notes
      summary: Find note by ID
      description: Returns a single note
      parameters:
        - name: noteId
          in: path
          required: true
          description: ID of note to return
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Note not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          
    put:
      tags:
        - notes
      summary: Update an existing note
      description: Tries to update a note and returns a message.
      parameters:
        - name: noteId
          in: path
          description: ID of note to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Note object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid ID or request body supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Note not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    
    delete:
      tags:
        - notes
      summary: Deletes a note
      description: Tries to delete a note and returns a message
      parameters:
        - name: noteId
          in: path
          description: Note id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Note not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: Eat Four Bananas in a Day
        content:
          type: string
          example: It might be too much for me..
    ApiResponse:
      type: object
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string